<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\ElementInterface     $element
 * @var string|null                       $label
 * @var array|null                        $labelAttributes
 * @var string|null                       $labelPosition
 * @var bool                              $renderErrors
 */
?>

<?php if ($element->getAttribute('type') != 'button' && $element->getAttribute('type') != 'submit'): ?>
    <div class="col-12 item">
        <div class="input-group">
            <?= $this->formElement()->render($element); ?>
            <div class="invalid-feedback order-last">Поле не валидно.</div>
            <button class="btn btn-outline-danger"
                    type="button"
                    onclick="delete_item(this)">
                <svg width="24"
                     height="24"
                     viewBox="0 0 32 32"
                     xmlns="http://www.w3.org/2000/svg">
                    <defs>
                        <style>.cls-1 {
                                fill: none;
                                stroke: currentColor;
                                stroke-linecap: round;
                                stroke-linejoin: round;
                                stroke-width: 2px;
                            }</style>
                    </defs>
                    <title></title>
                    <g id="cross">
                        <line class="cls-1"
                              x1="7"
                              x2="25"
                              y1="7"
                              y2="25"></line>
                        <line class="cls-1"
                              x1="7"
                              x2="25"
                              y1="25"
                              y2="7"></line>
                    </g>
                </svg>
            </button>
        </div>
    </div>
<?php else: ?>
    <div class="col-12">
        <?= $this->formElement()->render($element); ?>
    </div>
<?php endif; ?>
