<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\ElementInterface $element
 * @var string|null $label
 * @var array|null $labelAttributes
 * @var string|null $labelPosition
 * @var bool $renderErrors
 */

use Laminas\Form\Element\Button;

?>

<?php $classMap = [
    'surname'    => 'col-12 col-lg-4',
    'name'       => 'col-12 col-sm-6 col-lg-4',
    'patronymic' => 'col-12 col-sm-6 col-lg-4',

    'gender'   => 'col-12 col-sm-6 col-lg-4',
    'birthday' => 'col-12 col-sm-6 col-lg-4',

    'skype' => 'col-12 col-lg-4',
]; ?>

<div class="<?= $classMap[$element->getName()]; ?>">
    <?= (!$element instanceof Button) ? $this->formLabel($element) : ''; ?>
    <?= $this->formElement()->render($element); ?>
</div>
