<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\Element $element
 * @var string $label
 * @var array $labelAttributes
 * @var string $labelPosition
 * @var bool $renderErrors
 */

use Laminas\Form\Element\Button;

?>

<?php $classMap = [
    'surname'       => 'col-12 col-lg-4',
    'name'          => 'col-12 col-sm-6 col-lg-4',
    'patronymic'    => 'col-12 col-sm-6 col-lg-4',
    'gender'        => 'col-12 col-sm-6 col-lg-4',
    'birthday'      => 'col-12 col-sm-6 col-lg-4',
    'skype'         => 'col-12 col-lg-4',
]; ?>

<div class="<?= $classMap[$element->getName()]; ?>">
    <?php if (!$element instanceof Button)
        echo $this->formLabel($element); ?>
    <?= $this->formElement($element); ?>
</div>
