<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\ElementInterface     $element
 * @var string|null                       $label
 * @var array|null                        $labelAttributes
 * @var string|null                       $labelPosition
 * @var bool                              $renderErrors
 */

use Laminas\Form\Element;

?>

<div class="<?= $element->getAttribute('delimiter_class'); ?>">
    <?php if ($element instanceof Element\Button): ?>
        <?= $this->formElement()->render($element); ?>

    <?php elseif ($element instanceof Element\File): ?>
        <?= $this->formLabel($element); ?>
        <?= $this->formElement()->render($element); ?>

    <?php elseif ($element instanceof Element\Checkbox): ?>
        <div class="form-check">
            <?= $this->formElement()->render($element); ?>
            <?= $this->formLabel($element); ?>
        </div>

    <?php else: ?>
        <div class="form-floating">
            <?= $this->formElement()->render($element); ?>
            <?= $this->formLabel($element); ?>
        </div>
    <?php endif; ?>
</div>
