<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\Element $element
 * @var string $label
 * @var array $labelAttributes
 * @var string $labelPosition
 * @var bool $renderErrors
 */

use Laminas\Form\Element;

?>

<?php $classMap = [
    'photo'             => 'col-12',

    'surname'           => 'col-12 col-xl-4',
    'name'              => 'col-12 col-xl-4',
    'patronymic'        => 'col-12 col-xl-4',

    'gender'            => 'col-12 col-sm-6',
    'birthday'          => 'col-12 col-sm-6',

    'skype'             => 'col-12 col-lg-6',
    'position'          => 'col-12 col-lg-6',

    'status[admin]'     => 'col-12 col-md-6',
    'status[active]'    => 'col-12 col-md-6',

    'submit-button'     => 'col-12',
]; ?>

<div class="<?= $classMap[$element->getName()]; ?>">
    <?php if ($element instanceof Element\Button): ?>
        <?= $this->formElement()->render($element); ?>

    <?php elseif ($element instanceof Element\File): ?>
        <?= $this->formLabel($element); ?>
        <?= $this->formElement()->render($element); ?>

    <?php elseif ($element instanceof Element\Checkbox): ?>
        <div class="form-check">
            <?= $this->formElement()->render($element); ?>
            <?= $this->formLabel($element); ?>
        </div>

    <?php else: ?>
        <div class="form-floating">
            <?= $this->formElement()->render($element); ?>
            <?= $this->formLabel($element); ?>
        </div>
    <?php endif; ?>
</div>
