<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\ElementInterface $element
 * @var string|null $label
 * @var array|null $labelAttributes
 * @var string|null $labelPosition
 * @var bool $renderErrors
 */

use Laminas\Form\Element\Button;

?>

<div class="<?= $element->getAttribute('delimiter_class'); ?>">
    <?= (!$element instanceof Button) ? $this->formLabel($element) : ''; ?>
    <?= $this->formElement()->render($element); ?>
</div>
