<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\ElementInterface     $element
 * @var string|null                       $label
 * @var array|null                        $labelAttributes
 * @var string|null                       $labelPosition
 * @var bool                              $renderErrors
 */

use Laminas\Form\Element\Button;

?>

<div class="col-12">
    <?php if ($element instanceof Button): ?>
        <?= $this->formElement()->render($element); ?>
    <?php else: ?>
        <div class="form-floating">
            <?= $this->formElement()->render($element); ?>
            <?= $this->formLabel($element); ?>
            <div class="invalid-feedback">Поле не валидно.</div>
        </div>
    <?php endif; ?>
</div>
