<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<?php $element = $this->form->get($this->elementName); ?>
<?php $element->setAttribute('id', $this->elementName . '-field-' . $this->formName) ?>

<div class="form-floating">
    <?= $this->formElement($element) ?>
    <?= $this->formLabel($element) ?>
</div>
<div
        class="invalid-feedback d-none"
        id="<?= $this->elementName . '-error-' . $this->formName ?>"
>
</div>
