<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Laminas\Form\Element\Button;
use Laminas\Form\Element\Submit;

?>
<?php $isButton = $this->element instanceof Button || $this->element instanceof Submit; ?>

<div class="col-12">
    <?= ($isButton) ? null : '<div class="form-floating">'; ?>
    <?= $this->formElement()
        ->render($this->element); ?>
    <?= ($isButton) ? null : $this->formLabel($this->element); ?>
    <?= ($isButton) ? null : '</div>'; ?>
</div>
