<ul class="<?= $this->escapeHtml($this->navigation()->menu()->getUlClass()); ?>">
    <?php foreach ($this->container as $page) : ?>

        <?php $isDropdown = false;
        foreach ($page as $subpage) {
            $isDropdown = true;
            break;
        } ?>

        <?php $isSubpageActive = false;
        foreach ($page as $subpage) {
            if ($subpage->isActive()) {
                $isSubpageActive = true;
                break;
            }
        } ?>

        <?php if ($isDropdown): ?>
            <?php $dropdownId = uniqid('dropdown_', true); ?>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle<?= $this->escapeHtml(($isSubpageActive) ? ' active' : ''); ?>"
                   href="#"
                   id="<?= $this->escapeHtml($dropdownId); ?>"
                   role="button"
                   data-bs-toggle="dropdown"
                   aria-expanded="false">
                    <?= $this->escapeHtml($page->getLabel()); ?>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark"
                    aria-labelledby="<?= $this->escapeHtml($dropdownId); ?>">
                    <?php foreach ($page as $subpage) : ?>
                        <li>
                            <a href="<?= $this->escapeHtml($subpage->getHref()); ?>"
                               class="dropdown-item">
                                <?= $this->escapeHtml($subpage->getLabel()); ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        <?php else: ?>
            <li class="nav-item">
                <a href="<?= $this->escapeHtml($page->getHref()); ?>"
                   class="nav-link<?= $this->escapeHtml(($page->isActive()) ? ' active' : ''); ?>">
                    <?= $this->escapeHtml($page->getLabel()) ?>
                </a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
