<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\ElementInterface $element
 * @var string|null $label
 * @var array|null $labelAttributes
 * @var string|null $labelPosition
 * @var bool $renderErrors
 */
?>

<?php $classMap = [
    'message' => 'col',
    'submit-button' => 'col-auto',
]; ?>

<div class="<?= $classMap[$element->getName()]; ?>">
    <?= $this->formElement()->render($element); ?>
</div>
