<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\ElementInterface     $element
 * @var string|null                       $label
 * @var array|null                        $labelAttributes
 * @var string|null                       $labelPosition
 * @var bool                              $renderErrors
 */
?>

<div class="<?= $element->getAttribute('delimiter_class'); ?>">
    <?= $this->formElement()->render($element); ?>
</div>
