<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Model\Entity\User;

/** @var User[] $userList */
$userList = $this->userList;
?>
<div class="notification">The list is empty.</div>
<?php foreach ($userList as $user): ?>
    <div class="col-12">
        <div class="card p-3">
            <div class="row g-3">
                <div class="col-auto">
                    <img src="<?= $this->escapeHtml($user->getImagePath()); ?>"
                         class="user-photo img-fluid rounded"
                         alt="User's photo">
                </div>
                <div class="col">
                    <div class="row">
                        <div class="col-12">
                            <p class="h6 full-name"><?= $this->escapeHtml(
                                    implode(' ', [
                                        $user->getSurname() ?: '—',
                                        $user->getName() ?: '—',
                                        $user->getPatronymic() ?: '—',
                                    ])
                                ); ?></p>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Position:</span>
                            <span class="position"><?= $this->escapeHtml($user->getPositionName()); ?></span>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Age:</span>
                            <span class="age"><?= $this->escapeHtml($user->getAgeString()); ?></span>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Gender:</span>
                            <span class="gender"><?= $this->escapeHtml($user->getGenderString()); ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
