<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Model\Entity\User;

/** @var User[] $userList */
$userList = $this->userList;
?>
<?php foreach ($userList as $user): ?>
    <div class="col-12">
        <div class="card p-3">
            <div class="row g-3">
                <div class="col-auto">
                    <img src="<?= $this->escapeHtml(
                        file_exists($user->getImage()) ?
                            $user->getImagePath() :
                            '/img/headshot-1024x1024.jpg'
                    ); ?>"
                         class="user-photo img-fluid rounded"
                         alt="Фото пользователя">
                </div>
                <div class="col">
                    <div class="row">
                        <div class="col-12">
                            <p class="h6 full-name"><?= $this->escapeHtml(
                                    implode(' ', [
                                        $user->getSurname() ?: '—',
                                        $user->getName() ?: '—',
                                        $user->getPatronymic() ?: '—',
                                    ])
                                ); ?></p>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Должность:</span>
                            <span class="position"><?= $this->escapeHtml($user->getPositionName()); ?></span>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Возраст:</span>
                            <?php $age = 'Не указан'; ?>
                            <?php if ($user->getBirthday()): ?>
                                <?php $age = (new DateTime($user->getBirthday()))->diff(new DateTime())->y; ?>
                                <?php $ageLastNumber = $age % 10; ?>
                                <?php $old = ''; ?>
                                <?php $isExclusion = ($age % 100 >= 11) && ($age % 100 <= 14); ?>
                                <?php if ($ageLastNumber == 1): ?>
                                    <?php $old = "год"; ?>
                                <?php elseif ($ageLastNumber == 0 || $ageLastNumber >= 5): ?>
                                    <?php $old = "лет"; ?>
                                <?php elseif ($ageLastNumber >= 2 && $ageLastNumber <= 4): ?>
                                    <?php $old = "года"; ?>
                                <?php endif; ?>
                                <?php if ($isExclusion): ?>
                                    <?php $old = "лет"; ?>
                                <?php endif; ?>
                                <?php $age .= ' ' . $old; ?>
                            <?php endif; ?>
                            <span class="age"><?= $this->escapeHtml($age); ?></span>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Пол:</span>
                            <?php if ($user->getGender() == 1): ?>
                                <?php $gender = 'Мужской'; ?>
                            <?php elseif ($user->getGender() == 2): ?>
                                <?php $gender = 'Женский'; ?>
                            <?php else: ?>
                                <?php $gender = 'Не указан'; ?>
                            <?php endif; ?>
                            <span class="gender"><?= $this->escapeHtml($gender); ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>
