<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="col-12">
    <div class="card p-3">
        <div class="row g-3">
            <div class="col-auto">
                <img src="<?= $this->escapeHtml($this->photo); ?>"
                     class="user-photo img-fluid rounded"
                     alt="Фото пользователя">
            </div>
            <div class="col">
                <div class="row">
                    <div class="col-12">
                        <p class="h6 full-name"><?= $this->escapeHtml($this->fullname); ?></p>
                    </div>
                    <div class="col-auto">
                        <span class="text-secondary">Должность:</span>
                        <span class="position"><?= $this->escapeHtml($this->position); ?></span>
                    </div>
                    <div class="col-auto">
                        <span class="text-secondary">Возраст:</span>
                        <span class="age"><?= $this->escapeHtml($this->age); ?></span> лет
                    </div>
                    <div class="col-auto">
                        <span class="text-secondary">Пол:</span>
                        <span class="gender"><?= $this->escapeHtml($this->gender); ?></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
