<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="col-12<?= (!$this->isActive) ? ' card-gray-bg' : ''; ?>">
    <div class="card p-3">
        <div class="row g-3">
            <div class="col-auto">
                <img src="<?= $this->escapeHtml($this->photo); ?>"
                     class="user-photo img-fluid rounded"
                     alt="Фото пользователя">
            </div>
            <div class="col">
                <div class="row">
                    <div class="col-12">
                        <p class="h6 full-name"><?= $this->escapeHtml($this->fullname); ?>
                            <?php if ($this->isAdmin): ?>
                                <svg xmlns="http://www.w3.org/2000/svg"
                                     width="24"
                                     height="24"
                                     fill="currentColor"
                                     class="bi bi-key-fill ms-1"
                                     viewBox="0 0 16 16">
                                    <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"></path>
                                </svg>
                            <?php endif; ?>
                        </p>
                    </div>
                    <div class="col-auto">
                        <span class="text-secondary">Должность:</span>
                        <span class="position"><?= $this->escapeHtml($this->position); ?></span>
                    </div>
                    <div class="col-auto">
                        <span class="text-secondary">Возраст:</span>
                        <span class="age"><?= $this->escapeHtml($this->age); ?></span> лет
                    </div>
                    <div class="col-auto">
                        <span class="text-secondary">Пол:</span>
                        <span class="gender"><?= $this->escapeHtml($this->gender); ?></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
