<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Laminas\Form\ElementInterface $element
 * @var string|null $label
 * @var array|null $labelAttributes
 * @var string|null $labelPosition
 * @var bool $renderErrors
 */

use Laminas\Form\Element;

?>

<?php $classMap = [
    'position' => 'col-12',
    'gender'   => 'col-12',

    'age[min]' => 'col-6',
    'age[max]' => 'col-6',

    'fullname-phone-email' => 'col-12',

    'active' => 'col-12',
    'admin'  => 'col-12',
]; ?>

<?php if ($element->getAttribute('type') == 'number'): ?>
    <div class="<?= $classMap[$element->getName()]; ?>">
        <div class="input-group">
            <span class="input-group-text"><?= $this->escapeHtml($label); ?></span>
            <?= $this->formElement()->render($element); ?>
        </div>
    </div>
<?php else: ?>
    <div class="<?= $classMap[$element->getName()]; ?>">
        <?php if ($element instanceof Element\Button): ?>
            <?= $this->formElement()->render($element); ?>

        <?php elseif ($element instanceof Element\Textarea): ?>
            <div class="card p-3">
                <?= $this->formLabel($element); ?>
                <?= $this->formElement()->render($element); ?>
            </div>

        <?php else: ?>
            <div class="form-floating">
                <?= $this->formElement()->render($element); ?>
                <?= $this->formLabel($element); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
