<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Model\Entity\User;

/** @var User[] $userList */
$userList = $this->userList;

/** @var string $formName */
$formName = $this->formName;
?>

<?php foreach ($userList as $user): ?>
    <div class="col-12<?= (!$user->getStatus()['active']) ? ' card-gray-bg' : ''; ?>">
        <div class="card p-3">
            <div class="row g-3">
                <div class="col-auto">
                    <img src="<?= $this->escapeHtml($user->getImage() ?: '/img/headshot-1024x1024.jpg'); ?>"
                         class="user-photo img-fluid rounded"
                         alt="Фото пользователя">
                </div>
                <div class="col">
                    <div class="row">
                        <div class="col-12">
                            <p class="h6 full-name"><?= $this->escapeHtml(
                                    implode(' ', [
                                        $user->getSurname() ?: '—',
                                        $user->getName() ?: '—',
                                        $user->getPatronymic() ?: '—',
                                    ])
                                ); ?>
                                <?php if (
                                    $formName == 'AdminFilterForm' &&
                                    $user->getStatus()['admin']
                                ): ?>
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         width="24"
                                         height="24"
                                         fill="currentColor"
                                         class="bi bi-key-fill ms-1"
                                         viewBox="0 0 16 16">
                                        <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"></path>
                                    </svg>
                                <?php endif; ?>
                            </p>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Должность:</span>
                            <span class="position"><?= $this->escapeHtml($user->getPositionName()); ?></span>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Возраст:</span>
                            <span class="age"><?= $this->escapeHtml($user->getAgeString()); ?></span>
                        </div>
                        <div class="col-auto">
                            <span class="text-secondary">Пол:</span>
                            <span class="gender"><?= $this->escapeHtml($user->getGenderString()); ?></span>
                        </div>
                    </div>
                </div>
                <?php if ($formName == 'AdminFilterForm'): ?>
                    <div class="col-auto d-flex align-items-center">
                        <a href="<?= $this->url('admin/view-user-list/edit-user', ['id' => $user->getId()]); ?>"
                           class="btn btn-primary">Редактировать</a>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>
