<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Helper\FieldsetMapper;
use Laminas\Form\Element;

$element = $this->element;
/** @var Laminas\Form\ElementInterface $element */
$label = $this->label;
/** @var string|null $label */
$labelAttributes = $this->labelAttributes;
/** @var array|null $labelAttributes */
$labelPosition = $this->labelPosition;
/** @var string|null $labelPosition */
$renderErrors = $this->renderErrors;
/** @var bool $renderErrors */
?>

<?php if ($element->hasAttribute(FieldsetMapper::KEY)): ?>
<div class="<?= $element->getAttribute(FieldsetMapper::KEY); ?>">
    <?php endif; ?>

    <?php if (
        !isset($label)
        or $element instanceof Element\Button
        or $element instanceof Element\Submit
        or $element instanceof Element\Image
    ): ?>
        <?= $this->formElement()->render($element); ?>
    <?php else: ?>

        <?php if ($element instanceof Element\Number and strlen($label) <= 5): ?>
            <div class="input-group">
                <span class="input-group-text"><?= $this->escapeHtml($label); ?></span>
                <?= $this->formElement()->render($element); ?>
            </div>

        <?php elseif ($element instanceof Element\File or $element instanceof Element\Textarea): ?>
            <?= $this->formLabel($element); ?>
            <?= $this->formElement()->render($element); ?>

        <?php elseif ($element instanceof Element\Checkbox): ?>
            <?= $this->formElement()->render($element); ?>
            <?= $this->formLabel($element); ?>


        <?php elseif ($element instanceof Element\Number and strlen($label) <= 5): ?>
            <div class="input-group">
                <span class="input-group-text"><?= $this->escapeHtml($label); ?></span>
                <?= $this->formElement()->render($element); ?>
            </div>

        <?php else: ?>
            <div class="form-floating">
                <?= $this->formElement()->render($element); ?>
                <?= $this->formLabel($element); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>

    <?php if ($element->hasAttribute(FieldsetMapper::KEY)): ?>
</div>
<?php endif; ?>
