<?php
/**
 * @var $profileForm
 * @var $passwordForm
 */
$headTitle = 'Редактирование профиля';
$this->headTitle($headTitle);
$this->headLink()
    ->appendStylesheet($this->basePath('css/profile.css'));
$this->inlineScript()
    ->appendFile($this->basePath('js/validation.js'))
    ->appendFile($this->basePath('js/profile-edit.js'));
?>
<div class="card mb-2 mb-md-3 p-3 p-sm-4 p-md-5">
    <h1 class="mb-4 mb-md-5"><?= $this->escapeHtml($headTitle) ?></h1>
    <div class="row gy-3">
        <div class="col-12 col-lg-7 col-xl-8">

            <?php $form = $profileForm; ?>
            <?php $form->prepare(); ?>

            <?= $this->form()->openTag($form) ?>
            <div class="col-12">
                <?php $element = $form->get('photo'); ?>
                <?= $this->formLabel($element) ?>
                <?= $this->formElement($element) ?>
            </div>
            <div class="col-12 col-md-6">
                <?php $element = $form->get('surname'); ?>
                <?= $this->formLabel($element) ?>
                <?= $this->formElement($element) ?>
            </div>
            <div class="col-12 col-md-6">
                <?php $element = $form->get('name'); ?>
                <?= $this->formLabel($element) ?>
                <?= $this->formElement($element) ?>
            </div>
            <div class="col-12 col-md-6">
                <?php $element = $form->get('patronymic'); ?>
                <?= $this->formLabel($element) ?>
                <?= $this->formElement($element) ?>
            </div>
            <div class="col-6">
                <?php $element = $form->get('gender'); ?>
                <?= $this->formLabel($element) ?>
                <?= $this->formElement($element) ?>
            </div>
            <div class="col-6">
                <?php $element = $form->get('birthday'); ?>
                <?= $this->formLabel($element) ?>
                <?= $this->formElement($element) ?>
            </div>
            <div class="col-12 col-md-6">
                <?php $element = $form->get('skype'); ?>
                <?= $this->formLabel($element) ?>
                <?= $this->formElement($element) ?>
            </div>
            <div class="col-12">
                <?php $element = $form->get('submit'); ?>
                <?= $this->formSubmit($element) ?>
            </div>
            <?= $this->form()->closeTag() ?>
        </div>
        <div class="col">
            <div class="row gy-3">
                <div class="col-12">
                    <div class="form-label">Телефоны</div>
                    <div class="card p-3">
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-label">E-mail-ы</div>
                    <div class="card p-3">
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-label">Пароль</div>
                    <div class="card p-3">

                        <?php $form = $passwordForm; ?>
                        <?php $form->prepare(); ?>

                        <?= $this->form()->openTag($form) ?>

                        <div class="col-12">
                            <?php $element = $form->get('password-current'); ?>
                            <div class="form-floating">
                                <?= $this->formElement($element) ?>
                                <?= $this->formLabel($element) ?>
                            </div>
                            <div class="invalid-feedback d-none"
                                 id="password-current-error"></div>
                        </div>
                        <div class="col-12">
                            <?php $element = $form->get('password-new'); ?>
                            <div class="form-floating">
                                <?= $this->formElement($element) ?>
                                <?= $this->formLabel($element) ?>
                            </div>
                            <div class="invalid-feedback d-none"
                                 id="password-new-error"></div>
                        </div>
                        <div class="col-12">
                            <?php $element = $form->get('password-check'); ?>
                            <div class="form-floating">
                                <?= $this->formElement($element) ?>
                                <?= $this->formLabel($element) ?>
                            </div>
                            <div class="invalid-feedback d-none"
                                 id="password-check-error"></div>
                        </div>
                        <div class="col-12">
                            <?php $element = $form->get('submit'); ?>
                            <?= $this->formSubmit($element) ?>
                        </div>

                        <?= $this->form()->closeTag() ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
