<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var NewMessageForm                    $newMessageForm
 * @var Message[]                         $messages
 * @var UserRepositoryInterface           $userRepository
 * @var Application\Model\Entity\User     $userInfo
 * @var Application\Model\Entity\User     $buddyInfo
 */

use Application\Form\Messenger\NewMessageForm;
use Application\Model\Entity\Message;
use Application\Model\Repository\UserRepositoryInterface;

$this->inlineScript()
    ->appendFile($this->basePath('js/message-ajax.js'));
?>
<div class="row gy-3">
    <div class="col-12">
        <div class="row g-3 justify-content-between align-items-center">
            <div class="col-12 col-md-auto">
                <a href="<?= $this->url('user/view-dialog-list'); ?>"
                   class="btn btn-primary">Вернуться к диалогам</a>
            </div>
            <div class="col-12 col-md-auto">
                <div class="row g-2 align-items-center">
                    <div class="col-auto order-md-1">
                        <img src="<?= $this->escapeHtml($buddyInfo->getImagePath()); ?>"
                             class="buddy-photo img-fluid rounded"
                             alt="Фото пользователя">
                    </div>
                    <div class="col-auto order-md-0">
                        <span class="h6"><?= $this->escapeHtml(
                                implode(' ', [
                                    $buddyInfo->getSurname() ?: '—',
                                    $buddyInfo->getName() ?: '—',
                                    $buddyInfo->getPatronymic() ?: '—',
                                ])
                            ); ?></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <?= $this->userForm()->render($newMessageForm); ?>
    </div>
    <div class="col-12">
        <div class="row gy-3">
            <div class="notification">Сообщений нет.</div>
            <?php foreach ($messages as $message): ?>
                <?php if ($message->getUserId() == $userInfo->getId()) {
                    $user = $userInfo;
                } else {
                    $user = $buddyInfo;
                } ?>
                <div class="col-12">
                    <div class="row g-3">
                        <div class="col-auto">
                            <img src="<?= $this->escapeHtml($user->getImagePath()); ?>"
                                 class="message-avatar img-fluid rounded"
                                 alt="Фото пользователя">
                        </div>
                        <div class="col">
                            <div class="row g-1">
                                <div class="col-12">
                                    <div class="row gx-2">
                                        <div class="col-auto">
                                <span class="h6"><?= $this->escapeHtml(
                                        implode(' ', [
                                            $user->getSurname() ?: '—',
                                            $user->getName() ?: '—',
                                            $user->getPatronymic() ?: '—',
                                        ])
                                    ); ?></span>
                                        </div>
                                        <div class="col-auto">
                                            <span class="small"><?= $this->escapeHtml($message->getCreatedAt()); ?></span>
                                        </div>
                                        <?php if ($message->getOpenedAt()): ?>
                                            <div class="col-auto">
                                                <span class="small text-muted"><?= $this->escapeHtml($message->getOpenedAt()); ?></span>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <p class="m-0">
                                        <?= $this->escapeHtml($message->getContent()); ?>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-12 d-flex justify-content-center">
        <button class="btn btn-primary">Загрузить ещё</button>
    </div>
</div>
