<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var DialogFilterForm                  $dialogFilterForm
 * @var UserRepositoryInterface           $userRepository
 * @var PositionRepositoryInterface       $positionRepository
 * @var Application\Model\Entity\Dialog[] $dialogs
 */

use Application\Form\Messenger\DialogFilterForm;
use Application\Model\Repository\PositionRepositoryInterface;
use Application\Model\Repository\UserRepositoryInterface;

$this->inlineScript()
    ->appendFile($this->basePath('js/dialog-filter.js'))
?>
<div class="row g-3">
    <div class="col-12 col-lg-4 col col-xl-3">
        <div class="card p-3">
            <?= $this->userForm()->render($dialogFilterForm); ?>
        </div>
    </div>
    <div class="col">
        <div class="row g-3"
             id="dialog-list">
        </div>
    </div>
</div>
