<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var DialogFilterForm                  $dialogFilterForm
 * @var Application\Model\Entity\Dialog[] $dialogs
 */

use Application\Form\Messenger\DialogFilterForm;

?>
<div class="row g-3">
    <div class="col-12 col-lg-4 col col-xl-3">
        <div class="card p-3">
            <?= $this->userForm()->render($dialogFilterForm); ?>
        </div>
    </div>
    <div class="col">
        <div class="row g-3">
            <?php foreach ($dialogs as $dialog): ?>
                <?php // TODO: Добавить отображение карточки диалога. ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>
