<?php
/**
 * @var Application\Form\SignUpForm $signupForm
 */
?>

<?php $signupForm->prepare(); ?>

<?= $this->form()->openTag($signupForm) ?>
<div class="col-12">
    <?= $this->partial('partial/form_floating', [
        'form'        => $signupForm,
        'elementName' => 'email',
        'formName'    => 'signup',
    ]); ?>
</div>
<div class="col-12">
    <?= $this->partial('partial/form_floating', [
        'form'        => $signupForm,
        'elementName' => 'position',
        'formName'    => 'signup',
    ]); ?>
</div>
<div class="col-12">
    <?= $this->partial('partial/form_floating', [
        'form'        => $signupForm,
        'elementName' => 'password',
        'formName'    => 'signup',
    ]); ?>
</div>
<div class="col-12">
    <?= $this->partial('partial/form_floating', [
        'form'        => $signupForm,
        'elementName' => 'password-check',
        'formName'    => 'signup',
    ]); ?>
</div>
<div class="col-12">
    <?php $element = $signupForm->get('submit'); ?>
    <?= $this->formSubmit($element) ?>
</div>
<?= $this->form()->closeTag() ?>

<div class="row gy-2">
    <div class="col-12">
        <span>Уже есть аккаунт?</span>
        <button class="p-0 border-0 bg-transparent text-primary login-show">Войти</button>
    </div>
</div>
