<?php
/**
 * @var Application\Form\SignUpForm $signupForm
 */
?>

<?php $signupForm->prepare(); ?>

<?= $this->form()->openTag($signupForm) ?>
<div class="col-12">
    <?php $element = $signupForm->get('email'); ?>
    <div class="form-floating">
        <?= $this->formElement($element) ?>
        <?= $this->formLabel($element) ?>
    </div>
    <div class="invalid-feedback d-none"
         id="email-error-signup"></div>
</div>
<div class="col-12">
    <?php $element = $signupForm->get('position'); ?>
    <div class="form-floating">
        <?= $this->formElement($element) ?>
        <?= $this->formLabel($element) ?>
    </div>
    <div class="invalid-feedback d-none"
         id="position-error-signup"></div>
</div>
<div class="col-12">
    <?php $element = $signupForm->get('password'); ?>
    <div class="form-floating">
        <?= $this->formElement($element) ?>
        <?= $this->formLabel($element) ?>
    </div>
    <div class="invalid-feedback d-none"
         id="password-error-signup"></div>
</div>
<div class="col-12">
    <?php $element = $signupForm->get('password-check'); ?>
    <div class="form-floating">
        <?= $this->formElement($element) ?>
        <?= $this->formLabel($element) ?>
    </div>
    <div class="invalid-feedback d-none"
         id="password-check-error-signup"></div>
</div>
<div class="col-12">
    <?php $element = $signupForm->get('submit'); ?>
    <?= $this->formSubmit($element) ?>
</div>
<?= $this->form()->closeTag() ?>

<div class="row gy-2">
    <div class="col-12">
        <span>Уже есть аккаунт?</span>
        <button class="p-0 border-0 bg-transparent text-primary login-show">Войти</button>
    </div>
</div>
