<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var string $headTitleName
 */
?>
<?php $this->headTitle($headTitleName); ?>
<?php $this->headLink()
    ->appendStylesheet($this->basePath('css/login-signup-recover.css')); ?>
<?php $this->inlineScript()
    ->appendFile($this->basePath('js/validation.js'))
    ->appendFile($this->basePath('js/login-signup-recover.js')); ?>
<div class="card p-4"
     id="login-card">
    <h1 class="mb-3">Вход</h1>

    <?= $this->login ?>

</div>
<div class="card p-4"
     id="signup-card">
    <h1 class="mb-3">Регистрация</h1>

    <?= $this->signup ?>

</div>
<div class="card p-4"
     id="recover-card">
    <h1 class="mb-3">Восстановление</h1>

    <?= $this->recover ?>

</div>
