<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Application\Form\LoginForm $loginForm
 * @var Application\Form\SignUpForm $signUpForm
 * @var Application\Form\RecoverForm $recoverForm
 */

$this->headLink()
    ->appendStylesheet($this->basePath('css/login-signup-recover.css'));

$this->inlineScript()
    ->appendFile($this->basePath('js/switch-forms.js'));
?>

<?php $loginForm->prepare(); ?>

<div class="card p-4"
     id="login-card">
    <h1 class="mb-3">Вход</h1>
    <?= $this->form()->openTag($loginForm); ?>
    <?= $this->formCollection()->render($loginForm); ?>
    <?= $this->form()->closeTag(); ?>
    <div class="row gy-2 mt-2">
        <div class="col-12">
            <span>Нет аккаунта?</span>
            <button class="p-0 border-0 bg-transparent text-success signup-show">Зарегистрироваться</button>
        </div>
        <div class="col-12">
            <span>Забыли пароль?</span>
            <button class="p-0 border-0 bg-transparent text-danger recover-show">Восстановить</button>
        </div>
    </div>
</div>


<?php $signUpForm->prepare(); ?>

<div class="card p-4"
     id="signup-card">
    <h1 class="mb-3">Регистрация</h1>
    <?= $this->form()->openTag($signUpForm); ?>
    <?= $this->formCollection()->render($signUpForm); ?>
    <?= $this->form()->closeTag(); ?>
    <div class="row gy-2 mt-2">
        <div class="col-12">
            <span>Уже есть аккаунт?</span>
            <button class="p-0 border-0 bg-transparent text-primary login-show">Войти</button>
        </div>
    </div>
</div>


<?php $recoverForm->prepare(); ?>

<div class="card p-4"
     id="recover-card">
    <h1 class="mb-3">Восстановление</h1>
    <?= $this->form()->openTag($recoverForm); ?>
    <?= $this->formCollection()->render($recoverForm); ?>
    <?= $this->form()->closeTag(); ?>
    <div class="row gy-2 mt-2">
        <div class="col-12">
            <span>Вспомнили пароль?</span>
            <button class="p-0 border-0 bg-transparent text-primary login-show">Войти</button>
        </div>
    </div>
</div>
