<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var string                            $headTitleName
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php $this->headTitle($headTitleName); ?>
    <?= $this->headTitle('Информационный портал сотрудников')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico',
    ])
        ->prependStylesheet($this->basePath('css/login-signup-recover.css'))
        ->prependStylesheet($this->basePath('css/main.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.5.2.0-beta1.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>
<body>
<div class="container">
    <?= $this->content ?>
</div>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/switch-forms.js'))
    ->prependFile($this->basePath('js/enable-form-validation.js'))
    ->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
    ->prependFile($this->basePath('js/jquery-3.6.0.min.js')) ?>
</body>
</html>
