<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var $navbar
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this
        ->headTitle('Информационный портал сотрудников')
        ->setSeparator(' - ')
        ->setAutoEscape(false)
    ?>
    <?= $this
        ->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?= $this
        ->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
</head>
<body>
<div class="container">
    <div class="row">
        <header class="col-12">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <a class="navbar-brand"
                   href="#">ИнфоПортал</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse"
                     id="navbarNavDropdown">
                    <?= $this->navigation(($navbar) ?: "Laminas\Navigation\Default")
                        ->menu()
                        ->setUlClass('nav navbar-nav')
                        ->setPartial('partial/menu')
                        ->render() ?>
                </div>
            </nav>
        </header>
        <main class="col-12">
            <?= $this->content ?>
        </main>
    </div>
</div>
<?= $this
    ->inlineScript()
    ->prependFile($this->basePath('js/jquery-3.6.0.min.js'))
    ->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
?>
</body>
</html>
