<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var string                            $headTitleName
 * @var string                            $navbar
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php $this->headTitle($headTitleName); ?>
    <?= $this->headTitle('Information Portal for Employees')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico',
    ])
        ->prependStylesheet($this->basePath('css/main.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.5.2.0-beta1.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>
<body>
<div class="container">
    <div class="row">
        <header class="col-12">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <a class="navbar-brand"
                   href="<?= $this->url('home') ?>">InfoPortal</a>
                <button class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse"
                     id="navbarNavDropdown">
                    <?= $this->navigation($navbar ?? 'Laminas\Navigation\Default')->menu()
                        ->setUlClass('nav navbar-nav')
                        ->setPartial('partial/menu.phtml')
                        ->render() ?>
                </div>
            </nav>
        </header>
        <main class="col-12">
            <div class="card mb-2 mb-md-3 p-3 p-sm-4 p-md-5">
                <h1 class="mb-4 mb-md-5"><?= $this->escapeHtml($headTitleName); ?></h1>
                <?= $this->content ?>
            </div>
        </main>
    </div>
</div>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/enable-form-validation.js'))
    ->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
    ->prependFile($this->basePath('js/jquery-3.6.0.min.js')) ?>
</body>
</html>
