<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this
        ->headTitle('Информационный портал сотрудников')
        ->setSeparator(' - ')
        ->setAutoEscape(false)
    ?>
    <?= $this
        ->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?= $this
        ->headLink([
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>
</head>
<body class="d-flex">
<main class="w-100 m-auto">
    <?= $this->content ?>
</main>
<?= $this
    ->inlineScript()
    ->prependFile($this->basePath('js/jquery-3.6.0.min.js'))
    ->prependFile($this->basePath('js/bootstrap.bundle.min.js'))
?>
</body>
</html>
