<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Application\Form\EditPositionForm $editPositionForm
 */
$this->inlineScript()
    ->appendFile($this->basePath('js/collection-manipulation.js'));
?>

<?php $this->formRow()->setPartial('partial/collection-form'); ?>
<?php $this->formCollection()
    ->setTemplateWrapper('<span class="d-none" data-template="%s"></span>')
    ->setWrapper('<div class="col-12"><div%4$s>%2$s%1$s%3$s</div></div>'); ?>
<?= $this->form()->render($editPositionForm); ?>
