<?php
/**
 * @var $adminForm
 */
$headTitle = 'Список пользователей (Администратор)';
$this->headTitle($headTitle);
$this->layout()->setVariables([
    'navbar' => 'Laminas\Navigation\Admin',
]);
?>
<div class="card mb-2 mb-md-3 p-3 p-sm-4 p-md-5">
    <h1 class="mb-4 mb-md-5"><?= $this->escapeHtml($headTitle) ?></h1>
    <div class="row g-3">
        <div class="col-12">
            <div class="row align-items-center justify-content-between g-3">
                <div class="col-auto">
                    <p class="h5 mb-0">Показаны: 1-20 из 79</p>
                </div>
                <div class="col-auto">
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle"
                                type="button"
                                id="dropdown-sort"
                                data-bs-toggle="dropdown"
                                aria-expanded="false">
                            Сортировка
                        </button>
                        <ul class="dropdown-menu"
                            aria-labelledby="dropdown-sort">
                            <li><a class="dropdown-item"
                                   href="#">Должность</a></li>
                            <li><a class="dropdown-item"
                                   href="#">Пол</a></li>
                            <li><a class="dropdown-item"
                                   href="#">Возраст</a></li>
                            <li><a class="dropdown-item"
                                   href="#">ФИО</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="row g-3">
                <div class="col-12 col-lg-4 col col-xl-3">
                    <?php $adminForm->prepare(); ?>

                    <?= $this->form()->openTag($adminForm) ?>

                    <div class="col-12 col-sm-6 col-lg-12">
                        <div class="card p-3">
                            <?php $element = $adminForm->get('position'); ?>
                            <?= $this->formLabel($element) ?>
                            <?= $this->formElement($element) ?>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-lg-12">
                        <div class="card p-3">
                            <?php $element = $adminForm->get('gender'); ?>
                            <?= $this->formLabel($element) ?>
                            <?= $this->formElement($element) ?>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="card p-3">
                            <p class="form-label">Возраст</p>
                            <div class="row g-3">
                                <div class="col">
                                    <?php $element = $adminForm->get('min-age'); ?>
                                    <?= $this->formLabel($element) ?>
                                    <?= $this->formElement($element) ?>
                                </div>
                                <div class="col">
                                    <?php $element = $adminForm->get('max-age'); ?>
                                    <?= $this->formLabel($element) ?>
                                    <?= $this->formElement($element) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="card p-3">
                            <?php $element = $adminForm->get('fullname-phone-email'); ?>
                            <?= $this->formLabel($element) ?>
                            <?= $this->formElement($element) ?>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="card p-3">
                            <?php $element = $adminForm->get('active'); ?>
                            <?= $this->formLabel($element) ?>
                            <?= $this->formElement($element) ?>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="card p-3">
                            <?php $element = $adminForm->get('admin'); ?>
                            <?= $this->formLabel($element) ?>
                            <?= $this->formElement($element) ?>
                        </div>
                    </div>
                    <div class="col-12">
                        <?php $element = $adminForm->get('submit'); ?>
                        <?= $this->formElement($element) ?>
                    </div>

                    <?= $this->form()->closeTag() ?>
                </div>
                <div class="col">
                    <div class="row g-3">
                        <div class="col-12">
                            <div class="card p-3">
                                <div class="row g-3">
                                    <div class="col-auto">
                                        <img src="https://picsum.photos/900"
                                             class="user-photo img-fluid rounded"
                                             alt="Фото пользователя">
                                    </div>
                                    <div class="col">
                                        <div class="row">
                                            <div class="col-12">
                                                <p class="h6 full-name">Зубенко Михаил Петрович
                                                    <svg xmlns="http://www.w3.org/2000/svg"
                                                         width="24"
                                                         height="24"
                                                         fill="currentColor"
                                                         class="bi bi-key-fill ms-1"
                                                         viewBox="0 0 16 16">
                                                        <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                                                    </svg>
                                                </p>
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Должность:</span>
                                                <span class="position">Уборщик</span>
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Возраст:</span>
                                                <span class="age">49</span> лет
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Пол:</span>
                                                <span class="gender">Мужской</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 card-gray-bg">
                            <div class="card p-3">
                                <div class="row g-3">
                                    <div class="col-auto">
                                        <img src="https://picsum.photos/900"
                                             class="user-photo img-fluid rounded"
                                             alt="Фото пользователя">
                                    </div>
                                    <div class="col">
                                        <div class="row">
                                            <div class="col-12">
                                                <p class="h6 full-name">Зубенко Михаил Петрович</p>
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Должность:</span>
                                                <span class="position">Уборщик</span>
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Возраст:</span>
                                                <span class="age">49</span> лет
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Пол:</span>
                                                <span class="gender">Мужской</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center mt-3">
                        <div class="col-auto">
                            <nav aria-label="Page navigation">
                                <ul class="pagination mb-0">
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="#">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="#">1</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="#">2</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="#">3</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="#">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>