<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Application\Model\Entity\User[]   $userInfo
 * @var PositionRepositoryInterface       $positionRepository
 * @var int                               $maxPageCount
 * @var int                               $page
 * @var AdminFilterForm                   $adminFilterForm
 */

use Application\Form\Admin\AdminFilterForm;
use Application\Model\Repository\PositionRepositoryInterface;

$this->inlineScript()
    ->appendFile($this->basePath('js/user-filter.js'))
?>
<div class="row g-3">
    <div class="col-12">
        <div class="row align-items-center justify-content-between g-3">
            <div class="col-auto">
                <p class="h5 mb-0">
                    <?php $userCount = count($userInfo); ?>
                    <?= sprintf(
                        'Показаны: %d-%d из %d',
                        (1 + ($page - 1) * $maxPageCount),
                        min($page * $maxPageCount, $userCount),
                        $userCount,
                    ); ?>
                </p>
            </div>
            <div class="col-auto">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle"
                            type="button"
                            id="dropdown-sort"
                            data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Сортировка
                    </button>
                    <ul class="dropdown-menu"
                        aria-labelledby="dropdown-sort">
                        <li><a class="dropdown-item"
                               href="#">Должность</a></li>
                        <li><a class="dropdown-item"
                               href="#">Пол</a></li>
                        <li><a class="dropdown-item"
                               href="#">Возраст</a></li>
                        <li><a class="dropdown-item"
                               href="#">ФИО</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row g-3">
            <div class="col-12 col-lg-4 col col-xl-3">
                <div class="card p-3">
                    <?= $this->userForm()->render($adminFilterForm); ?>
                </div>
            </div>
            <div class="col">
                <div class="row g-3">
                    <?php foreach ($userInfo as $item): ?>
                        <div class="col-12<?= (!$item->getStatus()['active']) ? ' card-gray-bg' : ''; ?>">
                            <div class="card p-3">
                                <div class="row g-3">
                                    <div class="col-auto">
                                        <img src="<?= $this->escapeHtml($item->getImage() ?: '/img/headshot-1024x1024.jpg'); ?>"
                                             class="user-photo img-fluid rounded"
                                             alt="Фото пользователя">
                                    </div>
                                    <div class="col">
                                        <div class="row">
                                            <div class="col-12">
                                                <p class="h6 full-name"><?= $this->escapeHtml(
                                                        implode(' ', [
                                                            $item->getSurname() ?: '—',
                                                            $item->getName() ?: '—',
                                                            $item->getPatronymic() ?: '—',
                                                        ])
                                                    ); ?>
                                                    <?php if ($item->getStatus()['admin']): ?>
                                                        <svg xmlns="http://www.w3.org/2000/svg"
                                                             width="24"
                                                             height="24"
                                                             fill="currentColor"
                                                             class="bi bi-key-fill ms-1"
                                                             viewBox="0 0 16 16">
                                                            <path d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"></path>
                                                        </svg>
                                                    <?php endif; ?>
                                                </p>
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Должность:</span>
                                                <?php $position = $positionRepository->findPositionById($item->getPositionId()); ?>
                                                <span class="position"><?= $this->escapeHtml($position->getName()); ?></span>
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Возраст:</span>
                                                <?php $age = 'Не указан'; ?>
                                                <?php if ($item->getBirthday()): ?>
                                                    <?php $age = (new DateTime($item->getBirthday()))->diff(new DateTime())->y; ?>
                                                    <?php $ageLastNumber = $age % 10; ?>
                                                    <?php $old = ''; ?>
                                                    <?php $isExclusion = ($age % 100 >= 11) && ($age % 100 <= 14); ?>
                                                    <?php if ($ageLastNumber == 1): ?>
                                                        <?php $old = "год"; ?>
                                                    <?php elseif ($ageLastNumber == 0 || $ageLastNumber >= 5): ?>
                                                        <?php $old = "лет"; ?>
                                                    <?php elseif ($ageLastNumber >= 2 && $ageLastNumber <= 4): ?>
                                                        <?php $old = "года"; ?>
                                                    <?php endif; ?>
                                                    <?php if ($isExclusion): ?>
                                                        <?php $old = "лет"; ?>
                                                    <?php endif; ?>
                                                    <?php $age .= ' ' . $old; ?>
                                                <?php endif; ?>
                                                <span class="age"><?= $this->escapeHtml($age); ?></span>
                                            </div>
                                            <div class="col-auto">
                                                <span class="text-secondary">Пол:</span>
                                                <?php if ($item->getGender() == 1): ?>
                                                    <?php $gender = 'Мужской'; ?>
                                                <?php elseif ($item->getGender() == 2): ?>
                                                    <?php $gender = 'Женский'; ?>
                                                <?php else: ?>
                                                    <?php $gender = 'Не указан'; ?>
                                                <?php endif; ?>
                                                <span class="gender"><?= $this->escapeHtml($gender); ?></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-auto d-flex align-items-center">
                                        <a href="<?= $this->url('admin/view-user-list/edit-user', ['id' => $item->getId()]); ?>"
                                           class="btn btn-primary">Редактировать</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="row gx-2 justify-content-center mt-3">
                    <div class="col-auto d-flex align-items-center">
                        <label for="page">Страница</label>
                    </div>
                    <div class="col-auto">
                        <select id="page"
                                class="form-select">
                            <?php for ($i = 1; $i < $userCount / $maxPageCount + 1; $i++): ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                            <?php endfor; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
