<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Application\Model\Entity\User[]   $userInfo
 * @var PositionRepositoryInterface       $positionRepository
 * @var int                               $page
 * @var AdminFilterForm                   $adminFilterForm
 */

use Application\Controller\AdminController;
use Application\Form\Admin\AdminFilterForm;
use Application\Model\Repository\PositionRepositoryInterface;

$this->inlineScript()
    ->appendFile($this->basePath('js/user-filter.js'))
?>
<div class="row g-3">
    <div class="col-12">
        <div class="row align-items-center justify-content-between g-3">
            <div class="col-auto">
                <p class="h5 mb-0">
                    <?php $userCount = count($userInfo); ?>
                    <?= sprintf(
                        'Показаны: %d-%d из %d',
                        (1 + ($page - 1) * AdminController::maxPageCount),
                        min($page * AdminController::maxPageCount, $userCount),
                        $userCount,
                    ); ?>
                </p>
            </div>
            <div class="col-auto">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle"
                            type="button"
                            id="dropdown-sort"
                            data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Сортировка
                    </button>
                    <ul class="dropdown-menu"
                        aria-labelledby="dropdown-sort">
                        <li><a class="dropdown-item"
                               href="#">Должность</a></li>
                        <li><a class="dropdown-item"
                               href="#">Пол</a></li>
                        <li><a class="dropdown-item"
                               href="#">Возраст</a></li>
                        <li><a class="dropdown-item"
                               href="#">ФИО</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row g-3">
            <div class="col-12 col-lg-4 col col-xl-3">
                <div class="card p-3">
                    <?= $this->userForm()->render($adminFilterForm); ?>
                </div>
            </div>
            <div class="col">
                <div class="row g-3"
                     id="user-list">
                </div>
                <div class="row gx-2 justify-content-center mt-3">
                    <div class="col-auto d-flex align-items-center">
                        <label for="page">Страница</label>
                    </div>
                    <div class="col-auto">
                        <select id="page"
                                name="page"
                                class="form-select"
                                form="AdminFilterForm">
                            <?php for ($i = 1; $i < $userCount / AdminController::maxPageCount + 1; $i++): ?>
                                <option value="<?= $i ?>"><?= $i ?></option>
                            <?php endfor; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
