<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Application\Form\EditProfileForm $editProfileForm
 * @var Application\Form\ChangePasswordForm $changePasswordForm
 */
?>
<div class="row gy-3">
    <div class="col-12">
        <?php $this->formRow()->setPartial('partial/edit-profile'); ?>
        <?= $this->form()->render($editProfileForm); ?>
    </div>
    <div class="col-12">
        <div class="form-label">Телефоны</div>
        <div class="card p-3">
        </div>
    </div>
    <div class="col-12">
        <div class="form-label">E-mail-ы</div>
        <div class="card p-3">
        </div>
    </div>
    <div class="col-12">
        <div class="form-label">Пароль</div>
        <div class="card p-3">
            <?php $this->formRow()->setPartial('partial/floating-element'); ?>
            <?= $this->form()->render($changePasswordForm); ?>
        </div>
    </div>
</div>
