<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer     $this
 * @var array                                 $userInfo
 * @var int                                   $maxPageCount
 * @var int                                   $page
 * @var \Application\Form\User\UserFilterForm $userFilterForm
 */
?>
<div class="row g-3">
    <div class="col-12">
        <div class="row align-items-center justify-content-between g-3">
            <div class="col-auto">
                <p class="h5 mb-0">
                    <?php $userCount = count($userInfo); ?>
                    <?= sprintf('Показаны: %d-%d из %d',
                        (1 + ($page - 1) * $maxPageCount),
                        min($page * $maxPageCount, $userCount),
                        $userCount,
                    ); ?>
                </p>
            </div>
            <div class="col-auto">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle"
                            type="button"
                            id="dropdown-sort"
                            data-bs-toggle="dropdown"
                            aria-expanded="false">
                        Сортировка
                    </button>
                    <ul class="dropdown-menu"
                        aria-labelledby="dropdown-sort">
                        <li><a class="dropdown-item"
                               href="#">Должность</a></li>
                        <li><a class="dropdown-item"
                               href="#">Пол</a></li>
                        <li><a class="dropdown-item"
                               href="#">Возраст</a></li>
                        <li><a class="dropdown-item"
                               href="#">ФИО</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row g-3">
            <div class="col-12 col-lg-4 col col-xl-3">
                <div class="card p-3">
                    <?= $this->userForm()->render($userFilterForm); ?>
                </div>
            </div>
            <div class="col">
                <div class="row g-3">
                    <?= $this->partialLoop('partial/user-info.phtml', $userInfo); ?>
                </div>
                <div class="row justify-content-center mt-3">
                    <div class="col-auto">
                        <nav aria-label="Page navigation">
                            <ul class="pagination mb-0">
                                <li class="page-item">
                                    <a class="page-link"
                                       href="#">
                                        <span aria-hidden="true">&laquo;</span>
                                    </a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link"
                                       href="#">1</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link"
                                       href="#">2</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link"
                                       href="#">3</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link"
                                       href="#">
                                        <span aria-hidden="true">&raquo;</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
