<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var Application\Form\NewMessageForm $newMessageForm
 * @var array $messages
 * @var array $userInfo
 * @var array $buddyInfo
 */
?>
<div class="row gy-3">
    <div class="col-12">
        <div class="row g-3 justify-content-between align-items-center">
            <div class="col-12 col-md-auto">
                <a href="<?= $this->url('user/view-dialog-list'); ?>"
                   class="btn btn-primary">Вернуться к диалогам</a>
            </div>
            <div class="col-12 col-md-auto">
                <div class="row g-2 align-items-center">
                    <div class="col-auto order-md-1">
                        <img src="<?= $this->escapeHtml($buddyInfo['photo']); ?>"
                             class="buddy-photo img-fluid rounded"
                             alt="Фото пользователя">
                    </div>
                    <div class="col-auto order-md-0">
                        <span class="h6"><?= $this->escapeHtml($buddyInfo['fullname']); ?></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <?php $this->formRow()->setPartial('partial/new-message-form.phtml'); ?>
        <?= $this->form()->render($newMessageForm); ?>
    </div>
    <div class="col-12">
        <div class="row gy-3">
            <?= $this->partial('partial/message-list.phtml', [
                'messages' => $messages,
                'userInfo' => $userInfo,
                'buddyInfo' => $buddyInfo,
            ]); ?>
        </div>
    </div>
    <div class="col-12 d-flex justify-content-center">
        <button class="btn btn-primary">Загрузить ещё</button>
    </div>
</div>
