<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Controller\UserController;
use Application\Form\User\UserFilterForm;

/** @var UserFilterForm $userFilterForm */
$userFilterForm = $this->userFilterForm;

$this->inlineScript()
    ->appendFile($this->basePath('js/user-filter.js'))
?>
<div class="row g-3">
    <div class="col-12">
        <div class="row align-items-center justify-content-between g-3">
            <div class="col-auto">
                <p class="h5 mb-0"
                   id="display-info">Shown: <span id="shown"></span></p>
            </div>
            <div class="col-auto">
                <div class="row g-2">
                    <div class="col-auto d-flex align-items-center">
                        <label for="sort">Sort by:</label>
                    </div>
                    <div class="col-auto">
                        <select id="sort"
                                name="sort"
                                class="form-select">
                            <option value="fullname">Fullname</option>
                            <option value="position">Position</option>
                            <option value="age">Age</option>
                            <option value="gender">Gender</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <div class="row g-3">
            <div class="col-12 col-lg-4 col col-xl-3">
                <div class="card p-3">
                    <?= $this->userForm()->render($userFilterForm); ?>
                </div>
            </div>
            <div class="col">
                <div class="row g-3"
                     id="user-list">
                </div>
                <div class="row gx-2 justify-content-center mt-3">
                    <div class="col-auto d-flex align-items-center">
                        <label for="page">Page:</label>
                    </div>
                    <div class="col-auto">
                        <select id="page"
                                name="page"
                                class="form-select">
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    const MAX_USER_COUNT = <?= $this->escapeHtml(UserController::MAX_USER_COUNT); ?>;
</script>
