<?php
/**
 * @var Application\Form\LoginForm $loginForm
 */
?>

<?php $loginForm->prepare(); ?>

<?= $this->form()->openTag($loginForm) ?>
<div class="col-12">
    <?= $this->partial('partial/form_floating', [
        'form'        => $loginForm,
        'elementName' => 'email',
        'formName'    => 'login',
    ]); ?>
</div>
<div class="col-12">
    <?= $this->partial('partial/form_floating', [
        'form'        => $loginForm,
        'elementName' => 'password',
        'formName'    => 'login',
    ]); ?>
</div>
<div class="col-12">
    <?php $element = $loginForm->get('submit'); ?>
    <?= $this->formSubmit($element) ?>
</div>
<?= $this->form()->closeTag() ?>

<div class="row gy-2">
    <div class="col-12">
        <span>Нет аккаунта?</span>
        <button class="p-0 border-0 bg-transparent text-success signup-show">Зарегистрироваться</button>
    </div>
    <div class="col-12">
        <span>Забыли пароль?</span>
        <button class="p-0 border-0 bg-transparent text-danger recover-show">Восстановить</button>
    </div>
</div>
