<?php
/**
 * @var Application\Form\LoginForm $loginForm
 */
?>

<?php $loginForm->prepare(); ?>

<?= $this->form()->openTag($loginForm) ?>
<div class="col-12">
    <?=
    $this->formRow()
        ->setPartial('partial/form_floating')
        ->render($loginForm->get('email'))
    ?>
</div>
<div class="col-12">
    <?php $element = $loginForm->get('password'); ?>
    <div class="form-floating">
        <?= $this->formElement($element) ?>
        <?= $this->formLabel($element) ?>
    </div>
    <div class="invalid-feedback d-none"
         id="password-error-login"></div>
</div>
<div class="col-12">
    <?php $element = $loginForm->get('submit'); ?>
    <?= $this->formSubmit($element) ?>
</div>
<?= $this->form()->closeTag() ?>

<div class="row gy-2">
    <div class="col-12">
        <span>Нет аккаунта?</span>
        <button class="p-0 border-0 bg-transparent text-success signup-show">Зарегистрироваться</button>
    </div>
    <div class="col-12">
        <span>Забыли пароль?</span>
        <button class="p-0 border-0 bg-transparent text-danger recover-show">Восстановить</button>
    </div>
</div>
