<?php
/**
 * @var Application\Form\RecoverForm $recoverForm
 */
?>

<?php $recoverForm->prepare(); ?>

<?= $this->form()->openTag($recoverForm) ?>
<div class="col-12">
    <?= $this->partial('partial/form_floating', [
        'form'        => $recoverForm,
        'elementName' => 'email',
        'formName'    => 'recover',
    ]); ?>
</div>
<div class="col-12">
    <?php $element = $recoverForm->get('submit'); ?>
    <?= $this->formSubmit($element) ?>
</div>
<?= $this->form()->closeTag() ?>

<div class="row gy-2">
    <div class="col-12">
        <span>Вспомнили пароль?</span>
        <button class="p-0 border-0 bg-transparent text-primary login-show">Войти</button>
    </div>
</div>
