<?php
/**
 * @var Application\Form\RecoverForm $recoverForm
 */
?>

<?php $form = $recoverForm; ?>
<?php $form->prepare(); ?>

<?= $this->form()->openTag($form) ?>
<div class="col-12">
    <?php $element = $form->get('email'); ?>
    <div class="form-floating">
        <?= $this->formElement($element) ?>
        <?= $this->formLabel($element) ?>
    </div>
    <div class="invalid-feedback d-none"
         id="email-error-recover"></div>
</div>
<div class="col-12">
    <?php $element = $form->get('submit'); ?>
    <?= $this->formSubmit($element) ?>
</div>
<?= $this->form()->closeTag() ?>

<div class="row gy-2">
    <div class="col-12">
        <span>Вспомнили пароль?</span>
        <button class="p-0 border-0 bg-transparent text-primary login-show">Войти</button>
    </div>
</div>
