<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$this->layout('layout/layout.phtml');

/**
 * @var Home\Form\LoginForm $loginForm
 */
$loginForm = $this->loginForm;

/**
 * @var Home\Form\SignUpForm $signUpForm
 */
$signUpForm = $this->signUpForm;

/**
 * @var Home\Form\RecoverForm $recoverForm
 */
$recoverForm = $this->recoverForm;

$loginForm->setAttribute('action', $this->url());
$loginForm->prepare();

$signUpForm->setAttribute('action', $this->url());
$signUpForm->prepare();

$recoverForm->setAttribute('action', $this->url());
$recoverForm->prepare();
?>
